export { default as LoginScreen } from './LoginScreen'
export { default as RegisterScreen } from './RegisterScreen'
export { default as ResetPasswordScreen } from './ResetPasswordScreen'
export { default as Dashboard } from './Dashboard'
export { default as PageTreino} from './PageTreino'
export { default as PageTreinoIniciar} from './PageTreinoIniciar'
export { default as PageTreinoStart} from './PageTreinoStart'
export { default as MyEvolution} from './MyEvolution'
export { default as PageAluno} from './PageAluno'
